"enable syntax highlighting
syntax enable

"turn on line numbers
set number

"tabs will put in spaces instead of tab characters
set expandtab 
set tabstop=4

"mappings

" hit jk in insert mode to switch back to normal mode
inoremap jk <esc>

" make filename completion more like bash
set wildmode=longest,list,full
set wildmenu

" yank and other commands will automatically copy to the system clipboard
"set clipboard=unnamed

autocmd BufNewFile,BufReadPost *.md set filetype=markdown
