"turn on vim pathogen
execute pathogen#infect()

"enable syntax highlighting
syntax enable
set background=dark 
colorscheme solarized

"turn on line numbers
set number

"tabs will put in spaces instead of tab characters
set expandtab 
set tabstop=4

"make >> and << commands indent/unindent 4 spaces like a reasonable person would want
set shiftwidth=4

" make filename completion more like bash
set wildmode=longest,list,full
set wildmenu

" tell vim that .md means markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

"mappings

" hit jk in insert mode to switch back to normal mode
inoremap jk <esc>
inoremap <S-Tab> <C-d>
